function ScopeParameters = assignvarnames()
ScopeParameters                           = struct('Name','','Val', zeros(64,1));

'm',  % see # 64, below for intercept: 'BallBerry0'
'Cant',       %Added March 2017
'BallBerry0', % acccidentally left out of v1.7

ScopeParametersNames = {
    'Cab','Cca','Cdm','Cw','Cs','N','rho_thermal','tau_thermal',...
    'Vcmo','m','Type','kV','Rdparam','Tparam','fqe','spectrum',...
    'rss','rs_thermal','cs','rhos','lambdas','LAI','hc','zo','d',...
    'LIDFa','LIDFb','leafwidth','z','Rin','Ta','Rli','p','ea','u',...
    'Ca','Oa','rb','Cd','CR','CD1','Psicor','CSSOIL','rbs','rwc',...
    'startDOY','endDOY','LAT','LON','timezn','tts','tto','psi','SMC',...
    'Tyear','beta','kNPQs','qLs','stressfactor','Cant','BSMBrightness',...
    'BSMlat','BSMlon','BallBerry0'
}
end
