      MODULE LGRMODULE
         INTEGER, SAVE, POINTER ::ISCHILD
         INTEGER, SAVE, POINTER ::NBNODES,IBFLG
         INTEGER,SAVE,POINTER,DIMENSION(:)::ICOL,IROW,ILAY
         INTEGER,SAVE,POINTER,DIMENSION(:,:,:)::JMAT,IMAT,KMAT
         REAL,SAVE,POINTER,DIMENSION(:)::HBOLD,HBNEW
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::HK
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::VK
         DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:,:,:)::XX,YY,ZZ
        TYPE LGRTYPE
         INTEGER, POINTER ::ISCHILD,IBFLG,NBNODES
         INTEGER,POINTER,DIMENSION(:)::ICOL,IROW,ILAY
         INTEGER,POINTER,DIMENSION(:,:,:)::JMAT,IMAT,KMAT
         REAL,POINTER,DIMENSION(:)::HBOLD,HBNEW
         REAL,    POINTER,    DIMENSION(:,:,:) ::HK
         REAL,    POINTER,    DIMENSION(:,:,:) ::VK
         DOUBLEPRECISION,POINTER,DIMENSION(:,:,:)::XX,YY,ZZ
        END TYPE
        TYPE(LGRTYPE), SAVE::LGRDAT(10)
      END MODULE LGRMODULE
      
      MODULE Q3DMODULE
        INTEGER,SAVE,POINTER::ITERQ3D,NPILLAR,MXQ3DITER
        INTEGER,SAVE,POINTER,DIMENSION(:)::Ictrl0,Ictrl1,IBOT
        INTEGER,SAVE,POINTER,DIMENSION(:,:,:)::IPILLAR
        LOGICAL,SAVE,POINTER::CNVGH,CNVGF,Q3DF,LINEARF,ADAPTF
        DOUBLEPRECISION,SAVE,POINTER::RELAXH,RELAXF,HCLOSURE,
     1  FCLOSURE
        REAL,SAVE,POINTER::DELT0
        DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:)::ACELL,RRO,RRN,
     1  ZTB1,ZTB0,RrNstm,RrOstm
        REAL,SAVE,POINTER,DIMENSION(:,:)::BOT
        DOUBLEPRECISION,SAVE,allocatable::SYST(:,:),SSST(:,:)
        DOUBLEPRECISION,SAVE,allocatable::BOTSTMm(:,:)
        DOUBLEPRECISION,SAVE,allocatable::KPILRSTMm(:)
		
!        DOUBLEPRECISION,SAVE,allocatable::SYSTG(:,:),SSSTG(:,:)
!        DOUBLEPRECISION,SAVE,allocatable::BOTSTm(:,:)
!        DOUBLEPRECISION,SAVE,allocatable::KPLRSTm(:)		
		
        DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:,:)::HP00,HP0,HP1O,
     1  HP1N
        REAL,SAVE,POINTER,DIMENSION(:,:)::SY,SS
      TYPE Q3DTYPE
        INTEGER,POINTER::ITERQ3D,NPILLAR,MXQ3DITER
        INTEGER,POINTER,DIMENSION(:)::Ictrl0,Ictrl1,IBOT
        INTEGER,POINTER,DIMENSION(:,:,:)::IPILLAR
        LOGICAL,POINTER::CNVGH,CNVGF,Q3DF,LINEARF,ADAPTF
        DOUBLEPRECISION,POINTER::RELAXH,RELAXF,HCLOSURE,FCLOSURE
        REAL,POINTER::DELT0
        DOUBLEPRECISION,POINTER,DIMENSION(:)::ACELL,RRO,RRN,
     1  ZTB1,ZTB0,RrNstm,RrOstm
        REAL,POINTER,DIMENSION(:,:)::BOT
        DOUBLEPRECISION,POINTER,DIMENSION(:,:)::HP00,HP0,HP1O,HP1N
        REAL,POINTER,DIMENSION(:,:)::SY,SS
        DOUBLEPRECISION,allocatable::SYST(:,:),SSST(:,:)
        DOUBLEPRECISION,allocatable::BOTSTMm(:,:)
        DOUBLEPRECISION,allocatable::KPILRSTMm(:)
		
!        ! DOUBLEPRECISION,allocatable::SYSTG(:,:),SSSTG(:,:)
!        ! DOUBLEPRECISION,allocatable::BOTSTm(:,:)
!        ! DOUBLEPRECISION,allocatable::KPLRSTm(:)		
      ENDTYPE
      TYPE(Q3DTYPE),SAVE::Q3DDAT(10)
      END MODULE Q3DMODULE
      
      MODULE HYDRUSPARA 
      PARAMETER(
     ! imain=1,IWAT=2,ISLT=3,IRT=4,IHEAT=5,IWMAT=6,IWBC=7,IWNOD=8,
     ! IWBAL=9,IWOBS=10,ISBC=11,ISNOD=12,ISBAL=13,ISOBS=14,IHBC=15,
     ! IHNOD=16,IHBAL=17,IHOBS=18,IRUN=19,ICHECK=20,IRBC=21,IROBS=22,
     ! IRNOD=23)
      ENDMODULE
      
      MODULE HYDRUS
      CHARACTER*7,SAVE,POINTER::LUNIT,TUNIT
      CHARACTER*72,SAVE,POINTER::HEADING
      LOGICAL,SAVE,POINTER::
     .WaterF,SolutF,HeatF,RootF,WLayrF,qGWLF,ShortF,H_weight,
     . SeepF,AtmBCF,ConvgF,SatF,ChangF,Linear,ScrnF,weight,SStrsF,
     . SteadyF,Picard,UserF,plnmsF,plnmhF,plnmrF,plnmwF,bckspwF
      INTEGER,SAVE,POINTER::
     ! IHys,iPlevel,IRoot,ItCum,ItCumS,Iter,iTlevel,KBotCh,KBotH,
     ! KodBot,KodTop,KTopCh,KTopH,MaxIt,Nit,NItMax,NMat,
     ! NMatD,NObs,NParD,NReg,NTabD,NumNP,NUMNPD,icoup,
     ! iPLEVELBACK,KODTOP0
      DOUBLEPRECISION,SAVE,POINTER::
     ! Ampl,cBot,Courant,Cs,Ctol,cTop,CosAlf,
     ! DMul1,DMul2,dt,dtH,dtMax,dtMin,dtS,dtW,Epsi,hBot,
     ! hCritA,HPeclet,hRoot,hTabM,hTop,Omega,Omega_H,Omega0,Peclet,
     ! rBot,rRoot,rTop,Sv0C,Sv1C,Sv1T,SvBot,SvBotC,
     ! SvBotH,SvRoot,SvTop,SvTopC,SvTopH,t,tBC,tBCH,tBCR,tBCS,
     ! tEnd,Tol,tOld,Tolh,TpBot,TpTop,vBot,vRoot,vTop,
     ! TBC0,RTOP0,RBOT0,HTOP0,HBOT0,RTOP1,RBOT1,HTOP1,HBOT1,RTOP2,
     ! RBOT2,HTOP2,HBOT2,CTOP1,CTOP2,CBOT1,CBOT2,TPTOP1,TPTOP2,
     ! TPBOT1,TPBOT2,AMPL1,AMPL2,RROOT1,RROOT2,vinitW,vinitS,vinitH,
     ! CRROOT,CVROOT,SRTOP,TBC1,TBCS1,TBCH1,TBCR1,THRESH,dtBACK,
     1 dtFORWARD,SvTop0,SvBot0,SvRoot0,DTINIT
      
      INTEGER,SAVE,POINTER,DIMENSION(:)::
     ! iObs,iReg,Kappa,KappaO,MatNum,iEQ,iELE,INTERF,KPILLAR
      DOUBLEPRECISION,SAVE,POINTER::HPILLAR,HPILLAR00,HPILLAR0,HPILLAR1N
      DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:)::
     ! Ah,AhW,AK,AKS,AKW,Alpha,ATh,AThS,AThW,Bet,
     ! Beta,CapS,CAP,CONO,HTEMP,HOLD,Con,Conc,ConR,
     ! ConSat,g0,g1,gT1,hNew,hSat,hTab,P,phi,qt,
     ! qtOld,Salt,SaltO,Sink,Temp,ThN,ThO,ThR,ThRR,ThS,
     ! TPrint,v,vOld,x,xObs,z,DIFF,THNA,THNB,hBACK,
     1  THETA0,THETA1,QS
      DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:,:)::
     ! A,CHPAR,RSPAR,HPAR,CONTAB,CAPTAB,STAB,thTAB,DIFFTAB
      DOUBLEPRECISION,SAVE,POINTER,DIMENSION(:,:,:)::
     ! Par
      TYPE HYDRUSTYPE
      CHARACTER*7,POINTER::LUNIT,TUNIT
      CHARACTER*72,POINTER::HEADING
      LOGICAL,POINTER::
     .WaterF,SolutF,HeatF,RootF,WLayrF,qGWLF,ShortF,H_weight,
     . SeepF,AtmBCF,ConvgF,SatF,ChangF,Linear,ScrnF,weight,SStrsF,
     . SteadyF,Picard,UserF,plnmsF,plnmhF,plnmrF,plnmwF,bckspwF
      INTEGER,POINTER::
     ! IHys,iPlevel,IRoot,ItCum,ItCumS,Iter,iTlevel,KBotCh,KBotH,
     ! KodBot,KodTop,KTopCh,KTopH,MaxIt,Nit,NItMax,NMat,NMatD,
     ! NObs,NParD,NReg,NTabD,NumNP,NUMNPD,icoup,iPLEVELBACK,KODTOP0
      DOUBLEPRECISION,POINTER::
     ! Ampl,cBot,Courant,Cs,Ctol,cTop,CosAlf,
     ! DMul1,DMul2,dt,dtH,dtMax,dtMin,dtS,dtW,Epsi,hBot,
     ! hCritA,HPeclet,hRoot,hTabM,hTop,Omega,Omega_H,Omega0,Peclet,
     ! rBot,rRoot,rTop,Sv0C,Sv1C,Sv1T,SvBot,SvBotC,
     ! SvBotH,SvRoot,SvTop,SvTopC,SvTopH,t,tBC,tBCH,tBCR,tBCS,
     ! tEnd,Tol,tOld,Tolh,TpBot,TpTop,vBot,vRoot,vTop,
     ! TBC0,RTOP0,RBOT0,HTOP0,HBOT0,RTOP1,RBOT1,HTOP1,HBOT1,RTOP2,
     ! RBOT2,HTOP2,HBOT2,CTOP1,CTOP2,CBOT1,CBOT2,TPTOP1,TPTOP2,
     ! TPBOT1,TPBOT2,AMPL1,AMPL2,RROOT1,RROOT2,vinitW,vinitS,vinitH,
     ! CRROOT,CVROOT,SRTOP,TBC1,TBCS1,TBCH1,TBCR1,THRESH,
     ! dtBACK,dtFORWARD,SvTop0,SvBot0,SvRoot0,DTINIT
      INTEGER,POINTER,DIMENSION(:)::
     ! iObs,iReg,Kappa,KappaO,MatNum,iEQ,iELE,INTERF,KPILLAR
      DOUBLEPRECISION,POINTER::HPILLAR,HPILLAR00,HPILLAR0,HPILLAR1N
      DOUBLEPRECISION,POINTER,DIMENSION(:)::
     ! Ah,AhW,AK,AKS,AKW,Alpha,ATh,AThS,AThW,Bet,
     ! Beta,CapS,CAP,CONO,HTEMP,HOLD,Con,Conc,ConR,
     ! ConSat,g0,g1,gT1,hNew,hSat,hTab,P,phi,qt,
     ! qtOld,Salt,SaltO,Sink,Temp,ThN,ThO,ThR,ThRR,ThS,
     ! TPrint,v,vOld,x,xObs,z,DIFF,THNA,THNB,hBACK,
     1  THETA0,THETA1,QS
      DOUBLEPRECISION,POINTER,DIMENSION(:,:)::
     ! A,CHPAR,RSPAR,HPAR,CONTAB,CAPTAB,STAB,THTAB,DIFFTAB
      DOUBLEPRECISION,POINTER,DIMENSION(:,:,:)::
     ! Par
      ENDTYPE
      TYPE(HYDRUSTYPE),SAVE::HYDRUSDAT(100,10)
      ENDMODULE