%%% This script runs both Python package PyStemmusScope and MATLAB code of STEMMUS_SCOPE model

%% activate the pystemmusscope_3.8 environment
pe = pyenv;
if pe.Status ~= 'Loaded'
    pe = pyenv(...
        'Version','~/mamba/envs/pystemmusscope_3.8/bin/python',...
        "ExecutionMode", "OutOfProcess"...
    );
end

%% import statements
import py.PyStemmusScope.StemmusScope
PyStemmusScope_save = py.importlib.import_module('PyStemmusScope.save');

%% create an an instance of the model
%% cd STEMMUS_SCOPE/src
model = StemmusScope(...
    pyargs(...
        "config_file", "../config_file_snellius.txt",...
        "exe_file", "../exe/STEMMUS_SCOPE"...
    )...
);

%% setup the model
config_path = model.setup(...
    pyargs(...
        "WorkDir", "/scratch-shared/ecoextreml/stemmus_scope/",...
        "ForcingFileName", "ZA-Kru_2000-2002_FLUXNET2015_Met.nc",...
        "NumberOfTimeSteps","5"...
    )...
);

%% run the model using the function STEMMUS_SCOPE_exe
STEMMUS_SCOPE_exe(string(config_path));

%% save output in netcdf format
required_netcdf_variables = "../utils/csv_to_nc/required_netcdf_variables.csv";
nc_file_name = PyStemmusScope_save.to_netcdf(model.config, required_netcdf_variables);
fprintf('The output netcf file is in %s\n',string(nc_file_name));