name: Check code style

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  style:
    name: MISS_HIT checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install miss-hit
        run: |
          python3 -m pip install --upgrade pip miss-hit
      - name: Check for linter issues
        run: mh_lint src/ --brief
      - name: Check style against standards
        run: mh_style src/ --brief
